Remove np.float_ as a fill option
Running with NumPy 2.2.2 produces the following error:

    AttributeError: `np.float_` was removed in the NumPy 2.0 release. Use `np.float64` instead.

This removes the unsupported type.